### ISSUE TITLE
Errors when building Kimera-PGMO

### ISSUE THREAD

**Issue by HB-Liang** [MIT-SPARK/Kimera-PGMO#3]
I am trying to compile Hydra on Ubuntu 18.04 and ROS Melodic. Following the building instruction at [https://github.com/MIT-SPARK/Hydra](url), I ran into errors when building kimera-pgmo package.
Here is what the terminal show: 
![2023-07-11 14-44-08 的屏幕截图](https://github.com/MIT-SPARK/Kimera-PGMO/assets/114042103/71bd09fb-6d4b-441c-bfd4-aaa0a9a533d8)

**Comment by yunzc** [comment]
High, sorry for the late response. Were you able to figure out? Looks like there's a version mismatch with Kimera-RPGO.

**Comment by HB-Liang** [comment]
Sorry, I have no idea on version problem. Maybe change back to previous version can solve the error but I don't know which version to be changed.

**Comment by HB-Liang** [comment]
I do as @nathanhhughes said in https://github.com/MIT-SPARK/Hydra/issues/36 and make sure that RPGO package is the latest, but the issue still occurs.

**Comment by HB-Liang** [comment]
I do as @nathanhhughes said in https://github.com/MIT-SPARK/Hydra/issues/36 and make sure that RPGO package is the latest, but the issue still occurs.
