### ISSUE TITLE
dynamic semantic label

### ISSUE THREAD

**Issue by hyeonmin11** [MIT-SPARK/Kimera-PGMO#4]
Add dynamic semantic label to avoid integrating the depth - I could see this comment on Kimera-Semantics issue page.
Also I could found dynamic semantic mesh when I execute uHumans rosbag file using only Kimera-Semantics.

But I cannot find dynamic semantic mesh on Kimera-PGMO rviz. I want to check this part of the code(masking dynamic object). Can you explain me?

**Comment by yunzc** [comment]
Dynamic masking should be in Kimera-Semantics, for example, [this argument](https://github.com/MIT-SPARK/Kimera-Semantics/blob/master/kimera_semantics_ros/launch/kimera_semantics.launch#L122) in the launch file.
